<?php

namespace Database\Seeders;

use App\Models\Asset;
use App\Models\AssetCategory;
use App\Models\Location;
use App\Models\Supplier;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $categoryId = fn (string $name) => AssetCategory::where('name', $name)->first()?->id;
        $supplierId = fn (string $name) => Supplier::where('name', $name)->first()?->id;
        $locationId = fn (string $name) => Location::where('name', $name)->first()?->id;

        $assets = [
            // --- Hardware ---
            [
                'asset_tag'            => 'IT-0001',
                'name'                 => 'Laptop Dell Latitude 5540',
                'category_name'        => 'Hardware',
                'brand'                => 'Dell',
                'model'                => 'Latitude 5540',
                'serial_number'        => 'SN-DELL-001',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-01-15',
                'purchase_price'       => 1250.00,
                'supplier_name'        => 'Dell Technologies',
                'location_name'        => 'Oficina Central - Piso 2',
                'warranty_expiry_date' => '2028-01-15',
                'warranty_supplier'    => 'Dell Technologies',
                'notes'                => 'Laptop estándar para personal de TI.',
            ],
            [
                'asset_tag'            => 'IT-0002',
                'name'                 => 'Laptop Dell Latitude 5540',
                'category_name'        => 'Hardware',
                'brand'                => 'Dell',
                'model'                => 'Latitude 5540',
                'serial_number'        => 'SN-DELL-002',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-01-15',
                'purchase_price'       => 1250.00,
                'supplier_name'        => 'Dell Technologies',
                'location_name'        => 'Oficina Central - Piso 3',
                'warranty_expiry_date' => '2028-01-15',
                'warranty_supplier'    => 'Dell Technologies',
                'notes'                => 'Laptop para RH.',
            ],
            [
                'asset_tag'            => 'IT-0003',
                'name'                 => 'Laptop Lenovo ThinkPad X1',
                'category_name'        => 'Hardware',
                'brand'                => 'Lenovo',
                'model'                => 'ThinkPad X1 Carbon Gen 11',
                'serial_number'        => 'SN-LEN-001',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-02-01',
                'purchase_price'       => 1850.00,
                'supplier_name'        => 'Lenovo',
                'location_name'        => 'Oficina Central - Piso 1',
                'warranty_expiry_date' => '2029-02-01',
                'warranty_supplier'    => 'Lenovo',
                'notes'                => 'Premium para directorio.',
            ],
            [
                'asset_tag'            => 'IT-0004',
                'name'                 => 'Desktop HP EliteDesk 800',
                'category_name'        => 'Hardware',
                'brand'                => 'HP',
                'model'                => 'EliteDesk 800 G9',
                'serial_number'        => 'SN-HP-001',
                'status'               => 'available',
                'condition'            => 'good',
                'purchase_date'        => '2025-11-20',
                'purchase_price'       => 980.00,
                'supplier_name'        => 'HP Inc.',
                'location_name'        => 'Almacén Central',
                'warranty_expiry_date' => '2027-11-20',
                'warranty_supplier'    => 'HP Inc.',
                'notes'                => 'Equipo de escritorio estándar, sin asignar.',
            ],
            [
                'asset_tag'            => 'IT-0005',
                'name'                 => 'Desktop HP EliteDesk 800',
                'category_name'        => 'Hardware',
                'brand'                => 'HP',
                'model'                => 'EliteDesk 800 G9',
                'serial_number'        => 'SN-HP-002',
                'status'               => 'maintenance',
                'condition'            => 'fair',
                'purchase_date'        => '2025-08-10',
                'purchase_price'       => 980.00,
                'supplier_name'        => 'HP Inc.',
                'location_name'        => 'Oficina Central - Piso 2',
                'warranty_expiry_date' => '2027-08-10',
                'warranty_supplier'    => 'HP Inc.',
                'notes'                => 'En reparación por falla en la fuente de poder.',
            ],
            [
                'asset_tag'            => 'IT-0006',
                'name'                 => 'MacBook Pro 14"',
                'category_name'        => 'Hardware',
                'brand'                => 'Apple',
                'model'                => 'MacBook Pro 14" M3',
                'serial_number'        => 'SN-APP-001',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-03-01',
                'purchase_price'       => 2200.00,
                'supplier_name'        => 'Lenovo',
                'location_name'        => 'Sucursal Sur',
                'warranty_expiry_date' => '2029-03-01',
                'warranty_supplier'    => 'Lenovo',
                'notes'                => 'Equipo para diseño y marketing.',
            ],
            // --- Periféricos ---
            [
                'asset_tag'            => 'IT-0007',
                'name'                 => 'Monitor Dell 27" 4K',
                'category_name'        => 'Periféricos',
                'brand'                => 'Dell',
                'model'                => 'S2722QC',
                'serial_number'        => 'SN-MON-001',
                'status'               => 'stock',
                'condition'            => 'new',
                'purchase_date'        => '2026-04-10',
                'purchase_price'       => 450.00,
                'supplier_name'        => 'Dell Technologies',
                'location_name'        => 'Almacén Central',
                'warranty_expiry_date' => '2029-04-10',
                'warranty_supplier'    => 'Dell Technologies',
                'notes'                => 'Monitor nuevo en stock.',
            ],
            [
                'asset_tag'            => 'IT-0008',
                'name'                 => 'Keyboard Logitech MX Keys',
                'category_name'        => 'Periféricos',
                'brand'                => 'Logitech',
                'model'                => 'MX Keys',
                'serial_number'        => 'SN-KB-001',
                'status'               => 'stock',
                'condition'            => 'new',
                'purchase_date'        => '2026-04-10',
                'purchase_price'       => 120.00,
                'supplier_name'        => 'TechData Solutions',
                'location_name'        => 'Almacén Central',
                'notes'                => 'Teclado inalámbrico premium.',
            ],
            [
                'asset_tag'            => 'IT-0009',
                'name'                 => 'Headset Jabra Evolve2 40',
                'category_name'        => 'Periféricos',
                'brand'                => 'Jabra',
                'model'                => 'Evolve2 40',
                'serial_number'        => 'SN-HS-001',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-04-10',
                'purchase_price'       => 180.00,
                'supplier_name'        => 'TechData Solutions',
                'location_name'        => 'Oficina Central - Piso 2',
                'notes'                => 'Headset para llamado VoIP.',
            ],
            // --- Infraestructura ---
            [
                'asset_tag'            => 'IT-0010',
                'name'                 => 'Switch Cisco Catalyst 9300',
                'category_name'        => 'Infraestructura',
                'brand'                => 'Cisco',
                'model'                => 'Catalyst 9300-48P',
                'serial_number'        => 'SN-CIS-001',
                'status'               => 'assigned',
                'condition'            => 'good',
                'purchase_date'        => '2025-06-15',
                'purchase_price'       => 3200.00,
                'supplier_name'        => 'Cisco Systems',
                'location_name'        => 'Data Center',
                'warranty_expiry_date' => '2028-06-15',
                'warranty_supplier'    => 'Cisco Systems',
                'notes'                => 'Switch core del Data Center.',
            ],
            [
                'asset_tag'            => 'IT-0011',
                'name'                 => 'APC Smart-UPS 1500',
                'category_name'        => 'Infraestructura',
                'brand'                => 'APC',
                'model'                => 'SMT1500I',
                'serial_number'        => 'SN-UPS-001',
                'status'               => 'assigned',
                'condition'            => 'good',
                'purchase_date'        => '2025-06-20',
                'purchase_price'       => 750.00,
                'supplier_name'        => 'Dell Technologies',
                'location_name'        => 'Data Center',
                'warranty_expiry_date' => '2028-06-20',
                'warranty_supplier'    => 'Dell Technologies',
                'notes'                => 'UPS del rack principal.',
            ],
            // --- Móviles ---
            [
                'asset_tag'            => 'IT-0012',
                'name'                 => 'Smartphone Samsung Galaxy S24',
                'category_name'        => 'Dispositivos Móviles',
                'brand'                => 'Samsung',
                'model'                => 'Galaxy S24',
                'serial_number'        => 'SN-SAM-001',
                'status'               => 'assigned',
                'condition'            => 'new',
                'purchase_date'        => '2026-03-15',
                'purchase_price'       => 900.00,
                'supplier_name'        => 'Samsung Electronics',
                'location_name'        => 'Sucursal Sur',
                'warranty_expiry_date' => '2028-03-15',
                'warranty_supplier'    => 'Samsung Electronics',
                'notes'                => 'Smartphone corporativo para gerencia.',
            ],
            [
                'asset_tag'            => 'IT-0013',
                'name'                 => 'Tablet Samsung Galaxy Tab S9',
                'category_name'        => 'Dispositivos Móviles',
                'brand'                => 'Samsung',
                'model'                => 'Galaxy Tab S9',
                'serial_number'        => 'SN-SAM-002',
                'status'               => 'stock',
                'condition'            => 'new',
                'purchase_date'        => '2026-04-01',
                'purchase_price'       => 650.00,
                'supplier_name'        => 'Samsung Electronics',
                'location_name'        => 'Almacén Central',
                'warranty_expiry_date' => '2028-04-01',
                'warranty_supplier'    => 'Samsung Electronics',
                'notes'                => 'Tablet para presentaciones comerciales.',
            ],
        ];

        foreach ($assets as $data) {
            Asset::create([
                'asset_tag'            => $data['asset_tag'],
                'name'                 => $data['name'],
                'asset_category_id'    => $categoryId($data['category_name']),
                'brand'                => $data['brand'],
                'model'                => $data['model'],
                'serial_number'        => $data['serial_number'],
                'status'               => $data['status'],
                'condition'            => $data['condition'],
                'purchase_date'        => $data['purchase_date'],
                'purchase_price'       => $data['purchase_price'],
                'supplier_id'          => $supplierId($data['supplier_name']),
                'location_id'          => $locationId($data['location_name']),
                'warranty_expiry_date' => $data['warranty_expiry_date'] ?? null,
                'warranty_supplier_id' => isset($data['warranty_supplier']) ? $supplierId($data['warranty_supplier']) : null,
                'notes'                => $data['notes'],
            ]);
        }
    }
}
