<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    public function run(): void
    {
        $assets = [
            // --- Hardware ---
            [
                'asset_tag'       => 'IT-0001',
                'name'            => 'Laptop Dell Latitude 5540',
                'asset_category_id' => 1,
                'brand'           => 'Dell',
                'model'           => 'Latitude 5540',
                'serial_number'   => 'SN-DELL-001',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-01-15',
                'purchase_price'  => 1250.00,
                'supplier_id'     => 1,
                'location_id'     => 2,
                'warranty_expiry_date' => '2028-01-15',
                'warranty_supplier_id' => 1,
                'notes'           => 'Laptop estándar para personal de TI.',
            ],
            [
                'asset_tag'       => 'IT-0002',
                'name'            => 'Laptop Dell Latitude 5540',
                'asset_category_id' => 1,
                'brand'           => 'Dell',
                'model'           => 'Latitude 5540',
                'serial_number'   => 'SN-DELL-002',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-01-15',
                'purchase_price'  => 1250.00,
                'supplier_id'     => 1,
                'location_id'     => 3,
                'warranty_expiry_date' => '2028-01-15',
                'warranty_supplier_id' => 1,
                'notes'           => 'Laptop para RH.',
            ],
            [
                'asset_tag'       => 'IT-0003',
                'name'            => 'Laptop Lenovo ThinkPad X1',
                'asset_category_id' => 1,
                'brand'           => 'Lenovo',
                'model'           => 'ThinkPad X1 Carbon Gen 11',
                'serial_number'   => 'SN-LEN-001',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-02-01',
                'purchase_price'  => 1850.00,
                'supplier_id'     => 3,
                'location_id'     => 1,
                'warranty_expiry_date' => '2029-02-01',
                'warranty_supplier_id' => 3,
                'notes'           => 'Premium para directorio.',
            ],
            [
                'asset_tag'       => 'IT-0004',
                'name'            => 'Desktop HP EliteDesk 800',
                'asset_category_id' => 1,
                'brand'           => 'HP',
                'model'           => 'EliteDesk 800 G9',
                'serial_number'   => 'SN-HP-001',
                'status'          => 'available',
                'condition'       => 'good',
                'purchase_date'   => '2025-11-20',
                'purchase_price'  => 980.00,
                'supplier_id'     => 2,
                'location_id'     => 6,
                'warranty_expiry_date' => '2027-11-20',
                'warranty_supplier_id' => 2,
                'notes'           => 'Equipo de escritorio estándar, sin asignar.',
            ],
            [
                'asset_tag'       => 'IT-0005',
                'name'            => 'Desktop HP EliteDesk 800',
                'asset_category_id' => 1,
                'brand'           => 'HP',
                'model'           => 'EliteDesk 800 G9',
                'serial_number'   => 'SN-HP-002',
                'status'          => 'maintenance',
                'condition'       => 'fair',
                'purchase_date'   => '2025-08-10',
                'purchase_price'  => 980.00,
                'supplier_id'     => 2,
                'location_id'     => 2,
                'warranty_expiry_date' => '2027-08-10',
                'warranty_supplier_id' => 2,
                'notes'           => 'En reparación por falla en la fuente de poder.',
            ],
            [
                'asset_tag'       => 'IT-0006',
                'name'            => 'MacBook Pro 14"',
                'asset_category_id' => 1,
                'brand'           => 'Apple',
                'model'           => 'MacBook Pro 14" M3',
                'serial_number'   => 'SN-APP-001',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-03-01',
                'purchase_price'  => 2200.00,
                'supplier_id'     => 3,
                'location_id'     => 5,
                'warranty_expiry_date' => '2029-03-01',
                'warranty_supplier_id' => 3,
                'notes'           => 'Equipo para diseño y marketing.',
            ],
            // --- Periféricos ---
            [
                'asset_tag'       => 'IT-0007',
                'name'            => 'Monitor Dell 27" 4K',
                'asset_category_id' => 3,
                'brand'           => 'Dell',
                'model'           => 'S2722QC',
                'serial_number'   => 'SN-MON-001',
                'status'          => 'stock',
                'condition'       => 'new',
                'purchase_date'   => '2026-04-10',
                'purchase_price'  => 450.00,
                'supplier_id'     => 1,
                'location_id'     => 6,
                'warranty_expiry_date' => '2029-04-10',
                'warranty_supplier_id' => 1,
                'notes'           => 'Monitor nuevo en stock.',
            ],
            [
                'asset_tag'       => 'IT-0008',
                'name'            => 'Keyboard Logitech MX Keys',
                'asset_category_id' => 3,
                'brand'           => 'Logitech',
                'model'           => 'MX Keys',
                'serial_number'   => 'SN-KB-001',
                'status'          => 'stock',
                'condition'       => 'new',
                'purchase_date'   => '2026-04-10',
                'purchase_price'  => 120.00,
                'supplier_id'     => 6,
                'location_id'     => 6,
                'notes'           => 'Teclado inalámbrico premium.',
            ],
            [
                'asset_tag'       => 'IT-0009',
                'name'            => 'Headset Jabra Evolve2 40',
                'asset_category_id' => 3,
                'brand'           => 'Jabra',
                'model'           => 'Evolve2 40',
                'serial_number'   => 'SN-HS-001',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-04-10',
                'purchase_price'  => 180.00,
                'supplier_id'     => 6,
                'location_id'     => 2,
                'notes'           => 'Headset para llamado VoIP.',
            ],
            // --- Infraestructura ---
            [
                'asset_tag'       => 'IT-0010',
                'name'            => 'Switch Cisco Catalyst 9300',
                'asset_category_id' => 4,
                'brand'           => 'Cisco',
                'model'           => 'Catalyst 9300-48P',
                'serial_number'   => 'SN-CIS-001',
                'status'          => 'assigned',
                'condition'       => 'good',
                'purchase_date'   => '2025-06-15',
                'purchase_price'  => 3200.00,
                'supplier_id'     => 4,
                'location_id'     => 7,
                'warranty_expiry_date' => '2028-06-15',
                'warranty_supplier_id' => 4,
                'notes'           => 'Switch core del Data Center.',
            ],
            [
                'asset_tag'       => 'IT-0011',
                'name'            => 'APC Smart-UPS 1500',
                'asset_category_id' => 4,
                'brand'           => 'APC',
                'model'           => 'SMT1500I',
                'serial_number'   => 'SN-UPS-001',
                'status'          => 'assigned',
                'condition'       => 'good',
                'purchase_date'   => '2025-06-20',
                'purchase_price'  => 750.00,
                'supplier_id'     => 1,
                'location_id'     => 7,
                'warranty_expiry_date' => '2028-06-20',
                'warranty_supplier_id' => 1,
                'notes'           => 'UPS del rack principal.',
            ],
            // --- Móviles ---
            [
                'asset_tag'       => 'IT-0012',
                'name'            => 'Smartphone Samsung Galaxy S24',
                'asset_category_id' => 5,
                'brand'           => 'Samsung',
                'model'           => 'Galaxy S24',
                'serial_number'   => 'SN-SAM-001',
                'status'          => 'assigned',
                'condition'       => 'new',
                'purchase_date'   => '2026-03-15',
                'purchase_price'  => 900.00,
                'supplier_id'     => 8,
                'location_id'     => 5,
                'warranty_expiry_date' => '2028-03-15',
                'warranty_supplier_id' => 8,
                'notes'           => 'Smartphone corporativo para gerencia.',
            ],
            [
                'asset_tag'       => 'IT-0013',
                'name'            => 'Tablet Samsung Galaxy Tab S9',
                'asset_category_id' => 5,
                'brand'           => 'Samsung',
                'model'           => 'Galaxy Tab S9',
                'serial_number'   => 'SN-SAM-002',
                'status'          => 'stock',
                'condition'       => 'new',
                'purchase_date'   => '2026-04-01',
                'purchase_price'  => 650.00,
                'supplier_id'     => 8,
                'location_id'     => 6,
                'warranty_expiry_date' => '2028-04-01',
                'warranty_supplier_id' => 8,
                'notes'           => 'Tablet para presentaciones comerciales.',
            ],
        ];

        foreach ($assets as $asset) {
            Asset::create($asset);
        }
    }
}
