name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: write
    uses: nextup-py/deploy-actions/.github/workflows/laravel-deploy.yml@f2616b3a2838d3c9598f22d18de3d0a644da31ec # v1.1.0
    with:
      environment_name: itassets
      run_tests: true
      run_migrations: true
    secrets:
      SSH_HOST: ${{ secrets.ITASSETS_SSH_HOST }}
      SSH_PORT: ${{ secrets.ITASSETS_SSH_PORT }}
      SSH_USER: ${{ secrets.ITASSETS_SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.ITASSETS_SSH_PRIVATE_KEY }}
      DEPLOY_PATH: ${{ secrets.ITASSETS_DEPLOY_PATH }}
      APP_URL: ${{ secrets.ITASSETS_APP_URL }}
